# Níveis de verbosidade

/control/verbose 0
/run/verbose 0
/tracking/verbose 0
/process/em/verbose 0
/process/verbose 0
/process/had/verbose 0

# Seleção do modelo de cálculo de interações (Heed, PAI, PAIPhot)

/Detector/physics/setIonizationModel PAIPhot true

# Inicialização

/run/initialize

# Lançamento de partículas dentro do gás

/gun/particle e-
/gun/direction -1 0 0
/gun/position 0.0735 0.0735 0 m	
/gun/energy 200 eV
/run/beamOn 100